### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by fredyrincon** [nunoar/Android-HDP-connection-to-Nonin-Onyx-II-9560#1]
Hi, Any update about this code? Looking forward to get some examples working.

Thank you

**Comment by nunoar** [comment]
I don't have any devices to test with, at the moment, so I've set up an example based on this code: https://github.com/nunoar/Android-HDP-AND-UC-321PBT-C-Precision-Health-Scale/tree/develop

And made some changes that may help you.

The most relevant differences are the HEALTH_PROFILE_SOURCE_DATA_TYPE on the activity, and the run method on the service, which parses the data coming from the device, and would be the trickiest part to get. 

Check it out here:
https://github.com/nunoar/Android-HDP-connection-to-Nonin-Onyx-II-9560/tree/development

I hope it is helpful but If I get the chance to test it, I'll update the code, anyway.

**Comment by stefanhahmann** [comment]
You can also use this Test: https://github.com/stefanhahmann/BluetoothHDPtest/

**Comment by nikitasethgaba** [comment]
Hi 

I am new to Bluetooth Health profile, Your code looks quite helpful. I was testing your code against some other Bluetooth Oximeter on Android M.

I am getting below error:

_3-30 16:27:46.483 20233-20233/com.example.bluetooth.health W/BluetoothHealth: Proxy not attached to service 03-30 16:27:46.483 20233-20233/com.example.bluetooth.health D/BluetoothHealth: java.lang.Throwable at android.bluetooth.BluetoothHealth.connectChannelToSource(BluetoothHealth.java:241) at com.example.bluetooth.health.BluetoothHDPService.connectChannel(BluetoothHDPService.java:236) at com.example.bluetooth.health.BluetoothHDPService$IncomingHandler.handleMessage(BluetoothHDPService.java:172) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:158) at android.app.ActivityThread.main(ActivityThread.java:7230) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 03-30 16:27:50.363 20233-20233/com.example.bluetooth.health I/BluetoothHDPService: connectChannel(), connectChannelToSource=false_

Could you please help me resolving this issue.

**Comment by nunoar** [comment]
Hello,

I haven't worked in any of this for a while. I would recommend you getting in touch with the manufacturer of your device, some do help a lot, and it's worth trying.
